import { Button, ComboBox, Palette, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Installations, TextLevel } from "../global.slint";
import { Message } from "../components/message.slint";

export component HomePage inherits VerticalLayout {
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            alignment: start;

            Button {
                text: @tr("Check for updates");
                clicked => {
                    Installations.upgrade-ffnx()
                }
            }

            Button {
                text: @tr("Configure Mumba…");
                clicked => {
                    Installations.current-page = 1;
                }
            }

            Button {
                text: @tr("Game Options…");
                clicked => {
                    Installations.current-page = 2;
                }
            }
        }
    }
    Rectangle {
        background: Palette.background;
        vertical-stretch: 1;

        HorizontalBox {
            Image {
                source: @image-url("../../data/background.png");
            }
        }
    }
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            Message {}

            Button {
                text: @tr("Launch game");
                enabled: Installations.is-ready;
                primary: true;
                clicked => {
                    Installations.launch-game();
                }
            }
        }
    }
}
