import { Button, ComboBox, Palette, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Installations, TextLevel } from "../global.slint";

export component HomePage inherits VerticalLayout {
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            alignment: end;

            Button {
                text: @tr("Configure…");
                clicked => {
                    Installations.current-page = 2;
                }
            }
        }
    }
    Rectangle {
        background: Palette.background;
        vertical-stretch: 1;
    }
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            Rectangle {
                horizontal-stretch: 1;
                clip: true;
                background: Installations.task-text-type == TextLevel.error ? @linear-gradient(90deg, #ED3333 0%, #ED3333 95%, Palette.background.darker(0.2) 100%) : Palette.background.darker(0.2);

                HorizontalBox {
                    Text {
                        text: Installations.task-text;
                        horizontal-alignment: left;
                        font-weight: 700;
                        font-size: 1.1rem;
                        width: 100%;
                        color: Installations.task-text-type == TextLevel.error ? Colors.white : Palette.foreground;
                    }
                }
            }

            Button {
                text: @tr("Launch game");
                enabled: Installations.is-ready;
                clicked => {
                    Installations.launch-game();
                }
            }
        }
    }
}
