import { HorizontalBox, Button, Palette } from "std-widgets.slint";
import { OptionsDisplayPage } from "options/display.slint";
import { OptionsGamepadPage } from "options/gamepad.slint";
import { SideBar } from "../components/side_bar.slint";
import { Message } from "../components/message.slint";
import { Installations, Fluent } from "../global.slint";

export component OptionsPage inherits VerticalLayout {
    HorizontalLayout {
        vertical-stretch: 1;

        side-bar := SideBar {
            model: [Fluent.get-message("options-menu-display"), Fluent.get-message("options-menu-gamepad")];
        }

        if(side-bar.current-item == 0) : OptionsDisplayPage {}
        if(side-bar.current-item == 1) : OptionsGamepadPage {}
    }

    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            Message {}

            Button {
                text: Fluent.get-message("button-cancel");

                clicked => {
                    Installations.cancel-configure-ffnx();
                    Installations.current-page = 0;
                }
            }
            Button {
                text: Fluent.get-message("button-ok");
                primary: true;

                clicked => {
                    Installations.configure-ffnx();
                    Installations.current-page = 0;
                }
            }
        }
    }
}
