import { GroupBox, Palette, Button, StandardButton, HorizontalBox, LineEdit, VerticalBox, ComboBox } from "std-widgets.slint";
import { Installations } from "../global.slint";
import { Message } from "../components/message.slint";

export component SetupPage inherits VerticalLayout {
    Rectangle {
        VerticalBox {
            Text {
                text: @tr("Initial Setup");
                font-size: 20px;
            }
            GroupBox {
                title: @tr("FF8 EXE path");
                vertical-stretch: 0;

                HorizontalBox {
                    padding: 0px;
                    max-width: 664px;

                    game-exe-path := LineEdit {
                        text: Installations.game-exe-path;
                    }

                    Button {
                        text: @tr("Browse…");
                        clicked => {
                            game-exe-path.text = Installations.browse-game(game-exe-path.text);
                        }
                    }
                }
            }
            GroupBox {
                title: @tr("Canal de mise à jour");
                vertical-stretch: 0;

                HorizontalBox {
                    padding: 0px;
                    max-width: 664px;

                    update-channel := ComboBox {
                        model: [@tr("Stable"), @tr("Beta"), @tr("Alpha")];
                        current-index: Installations.update-channel;
                    }
                }
            }
        }
    }
    Rectangle {
        vertical-stretch: 1;
    }
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            Message {}

            StandardButton {
                kind: ok;
                clicked => {
                    Installations.setup(game-exe-path.text, update-channel.current-index);
                    Installations.current-page = 0;
                }
            }
        }
    }
}
