import { GroupBox, Palette, Button, HorizontalBox, LineEdit, VerticalBox, ComboBox } from "std-widgets.slint";
import { Installations, Fluent } from "../global.slint";
import { Message } from "../components/message.slint";

export component SetupPage inherits VerticalLayout {
    in-out property <bool> show-restart-message : false;

    Rectangle {
        VerticalBox {
            Text {
                text: Fluent.get-message("setup-page-title");
                font-size: 20px;
                wrap: word-wrap;
            }
            GroupBox {
                title: Fluent.get-message("config-group-ff8-exe-path");
                vertical-stretch: 0;

                HorizontalBox {
                    padding: 0px;
                    max-width: 664px;

                    game-exe-path := LineEdit {
                        text: Installations.game-exe-path;
                    }

                    Button {
                        text: Fluent.get-message("button-browse");
                        clicked => {
                            game-exe-path.text = Installations.browse-game(game-exe-path.text);
                        }
                    }
                }
            }
            GroupBox {
                title: Fluent.get-message("config-group-update-channel");
                vertical-stretch: 0;

                HorizontalBox {
                    padding: 0px;
                    max-width: 664px;

                    update-channel := ComboBox {
                        model: [
                            Fluent.get-message("update-channel-stable"),
                            Fluent.get-message("update-channel-beta"),
                            Fluent.get-message("update-channel-alpha")
                        ];
                        current-index: Installations.update-channel;
                    }
                }
            }
            GroupBox {
                title: Fluent.get-message("config-group-language");
                vertical-stretch: 0;

                VerticalLayout {
                    HorizontalBox {
                        padding: 0px;
                        max-width: 664px;

                        language := ComboBox {
                            model: [
                                Fluent.get-message("language-english"),
                                Fluent.get-message("language-french")
                            ];
                            current-index: Installations.language;

                            selected() => {
                                root.show-restart-message = true;
                                Installations.set-current-lang(self.current-index);
                            }
                        }
                    }

                    if root.show-restart-message : Text {
                        text: Fluent.get-message("config-language-must-restart");
                        wrap: word-wrap;
                    }
                }
            }
        }
    }
    Rectangle {
        vertical-stretch: 1;
    }
    Rectangle {
        background: Palette.background.darker(0.2);

        HorizontalBox {
            Message {}

            Button {
                text: Fluent.get-message("button-cancel");
                visible: Installations.is-initialized;

                clicked => {
                    Installations.current-page = 0;
                }
            }

            Button {
                text: Fluent.get-message("button-ok");
                primary: true;

                clicked => {
                    Installations.setup(game-exe-path.text, update-channel.current-index, language.current-index);
                    Installations.current-page = 0;
                }
            }
        }
    }
}
