import { Button, ComboBox, StyleMetrics, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { SetupPage } from "pages/setup.slint";
import { OptionsPage } from "pages/options.slint";
import { SelectDirPage } from "pages/select_dir.slint";
import { HomePage } from "pages/home.slint";
import { Installations, Fluent } from "global.slint";

export { Installations, Fluent }

export component AppWindow inherits Window {
    preferred-width: 640px;
    preferred-height: 480px;
    title: Fluent.get-message("window-title");
    icon: @image-url("../data/icon.png");

    if Installations.current-page == 0 : HomePage {}
    if Installations.current-page == 1 : SetupPage {}
    if Installations.current-page == 2 : OptionsPage {}
    if Installations.current-page == 3 : SelectDirPage {}
}
