import { HorizontalBox, Palette } from "std-widgets.slint";
import { Installations, TextLevel } from "../global.slint";

export component Message inherits Rectangle {
    horizontal-stretch: 1;
    clip: true;
    background: Installations.task-text-type == TextLevel.error ? @linear-gradient(90deg, #ED3333 0%, #ED3333 95%, Palette.background.darker(0.2) 100%) : Palette.background.darker(0.2);

    HorizontalBox {
        Text {
            text: Installations.task-text;
            horizontal-alignment: left;
            font-weight: 700;
            font-size: 1.1rem;
            width: 100%;
            color: Installations.task-text-type == TextLevel.error ? Colors.white : Palette.foreground;
        }
    }
}
