import { Switch, ScrollView, SpinBox, ComboBox, GroupBox, Button, Palette, HorizontalBox, GridBox, LineEdit, VerticalBox } from "std-widgets.slint";
import { Installations, Fluent } from "../../global.slint";

export component OptionsGamepadPage inherits VerticalLayout {
    VerticalBox {
        Text {
            text: Fluent.get-message("options-page-gamepad-title");
            font-size: 20px;
            wrap: word-wrap;
        }
    }

    ScrollView {
        vertical-stretch: 1;
        horizontal-stretch: 1;

        VerticalBox {
            max-width: 664px;

            GroupBox {
                title: Fluent.get-message("config-group-inputs");
                vertical-stretch: 0;

                VerticalBox {
                    Switch {
                        text: Fluent.get-message("show-ps1-gamepad-icons");
                        checked: Installations.ffnx-config.ff8_use_gamepad_icons;

                        toggled() => {
                            Installations.set-ffnx-config-bool("ff8_use_gamepad_icons", self.checked)
                        }
                    }
                }
            }

            Image {
                source: @image-url("../../../data/gamepad_layout.svg");
                max-width: 664px;
                max-height: 664px;
            }
        }

        Rectangle {
            vertical-stretch: 1;
        }
    }
}
